### ISSUE TITLE
[tracking] Logging and status

### ISSUE THREAD

**Issue by roberth** [nixops4/nixops4#54]
- [x] Span-based logging with `tracing` library ecosystem
- [x] Forwarding from `nixops4-eval`
- [x] Combined logging and progress TUI
- [x] Custom panic handler
- [ ] Add more spans and fields
- [ ] Correctly ingest `tracing-subscriber`'s ANSI formatting codes when rendering TUI `Span`s
- [ ] Filter out overly verbose spans (in the UI)
- [ ] Get span info from Nix `Activity`s
- [ ] Develop the activity list into a proper tree widget like https://crates.io/crates/tui-tree-widget
- [ ] Use ANSI scroll regions to avoid flickering when logs are written to screen
- [ ] Machine-readable logging mode; OpenTelemetry JSON?
